# basic options
title: A School Portfolio
author: Justin Man
email: justinm517@gmail.com
description: This is a portfolio I've made to showcase the media work I've done so far in my academic life. 
twitter_username: thedank27
github_username:  justinm517

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
